# Generated by Django 4.1.1 on 2022-10-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todos_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='completed',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
